baseURL = 'https://g4s8.github.io/gdf-am-2025/'
languageCode = 'en-us'
title = 'Go Beyond Models'

theme = ["github.com/joshed-io/reveal-hugo"]

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true


[params.reveal_hugo]
# theme = "white"
theme = "robot-lung"
# custom_theme = "robot-lung.css"
highlight_theme = "github"
slide_number = "c/t"
transition = 'slide'
custom_css = "css/custom.css"

# choose between Hugo compile-time or Highlight.js
# syntax highlighting for code inside of code fences
[markup.highlight]
codeFences = true  # use highlight.js
# codeFences = true  # use hugo highlighting at compile time
style = "tango"  # set a style for hugo highlighting


