baseURL = 'https://g4s8.github.io/gdf-am-2025/'
languageCode = 'en-us'
title = 'Go Beyond Models'

theme = ["github.com/joshed-io/reveal-hugo"]

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true


[params.reveal_hugo]
theme = "robot-lung"
highlight_theme = "github"
slide_number = "c/t"
transition = 'slide'
custom_css = "css/custom.css"

[markup.highlight]
codeFences = true  # use highlight.js
style = "tango"  # set a style for hugo highlighting


